1. Main prints "hello"
2. Main executes notThrowit
3. notThrowit executes throwit
4. throwit prints "throwit"
5. throwit throws RuntimeException
6. throwit does not have any exception handler so
going to the method that called throwit()  in this case it is notThrowit
7. notThrowit does not have any exception handler
so going to the method that called notThrowit()  in this case it is main
8. main method has Exception handler which catches RuntimeException
  so it is executed and prints "caught"
9. Finally block is executed in main -> print finally
10. Try catch block completed with no unhandled exceptions
  so program continues as expected and prints after
